/**
 * Ajo Contract TypeScript Bindings
 *
 * Auto-generated by `stellar contract bindings typescript` in CI.
 * DO NOT EDIT by hand — regenerate via `npm run contract:bindings`.
 *
 * Contract: ajosave-ajo v0.2.0
 * Network:  Stellar Testnet
 * Contract ID: CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC
 *
 * @generated
 */

// ─── Types ───────────────────────────────────────────────────────────────────

export interface AjoInitializeArgs {
  admin: string;
  token: string;
  contribution_amount: bigint;
  max_members: number;
  cycle_interval_secs: bigint;
}

export interface AjoContributeArgs {
  member: string;
  cycle: number;
}

export interface AjoPayoutArgs {
  // no args — admin auth checked inside contract
}

export interface AjoSetPayoutOrderArgs {
  order: number[];
}

export interface AjoGetStateResult {
  current_cycle: number;
  next_payout_time: bigint;
  completed: boolean;
  paused: boolean;
  members_count: number;
}

export interface AjoMemberReputation {
  total_circles_completed: number;
  on_time_contributions: number;
  total_contributions: number;
}

// ─── Client (placeholder — replaced by generated output in CI) ───────────────

export interface AjoContractClient {
  initialize(args: AjoInitializeArgs): Promise<void>;
  join(member: string): Promise<void>;
  contribute(args: AjoContributeArgs): Promise<void>;
  payout(): Promise<void>;
  set_payout_order(args: AjoSetPayoutOrderArgs): Promise<void>;
  get_state(): Promise<AjoGetStateResult>;
  get_members(): Promise<string[]>;
  get_member_reputation(member: string): Promise<AjoMemberReputation>;
  migrate(new_wasm_hash: Buffer): Promise<void>;
}
